name: versioning
on:
   [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: git ls-files --format='%(objectname) %(objectsize) %(path)' > version
      - uses: EndBug/add-and-commit@v9